services:
  payment-postgres:
    image: postgres:16-alpine
    container_name: payment-gateway-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_gateway_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_gateway_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: payment-gateway
    entrypoint: ["/usr/local/bin/init.sh", "air", "-c", ".air.toml"]
    environment:
      - GATEWAY_PRIMARY__ENV=development
      - GATEWAY_SERVER__PORT=8080
      - GATEWAY_SERVER__READ_TIMEOUT=15s
      - GATEWAY_SERVER__WRITE_TIMEOUT=15s
      - GATEWAY_SERVER__IDLE_TIMEOUT=60s
      - GATEWAY_DATABASE__HOST=payment-postgres
      - GATEWAY_DATABASE__PORT=5432
      - GATEWAY_DATABASE__USER=postgres
      - GATEWAY_DATABASE__PASSWORD=postgres
      - GATEWAY_DATABASE__NAME=payment_gateway_db
      - GATEWAY_DATABASE__SSL_MODE=disable
      - GATEWAY_DATABASE__MAX_OPEN_CONNS=25
      - GATEWAY_DATABASE__MAX_IDLE_CONNS=5
      - GATEWAY_DATABASE__CONN_MAX_LIFETIME=5m
      - GATEWAY_DATABASE__CONN_MAX_IDLE_TIME=5m
      - GATEWAY_BANK_CLIENT__BANK_BASE_URL=http://host.docker.internal:8787
      - GATEWAY_BANK_CLIENT__BANK_CONN_TIMEOUT=30s
      - GATEWAY_RETRY__BASE_DELAY=1
      - GATEWAY_RETRY__MAX_RETRIES=3
      - GATEWAY_RETRY__MAX_BACKOFF=10
      - GATEWAY_WORKER__INTERVAL=30s
      - GATEWAY_WORKER__BATCH_SIZE=100
      - GATEWAY_LOGGER__LEVEL=info
    ports:
      - "8081:8080"
    volumes:
      - ..:/app
      - gateway_tmp:/app/tmp
    depends_on:
      payment-postgres:
        condition: service_healthy
    networks:
      - payment-network
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    restart: unless-stopped


networks:
  payment-network:
    driver: bridge

volumes:
  postgres_data:
    name: payment-gateway-postgres-data
  gateway_tmp: